development:
  defaults:
    time_filter: day
    limit: 1
    enabled: true

  subreddits:
    - name: fuckubisoft

production:
  defaults:
    time_filter: day
    limit: 1 # top posts to fetch per subreddit when limit is not set on the entry
    enabled: true

  subreddits:
    - name: AITAH
      limit: 1
    - name: AmIOverreacting
      limit: 1
    - name: EntitledPeople
      limit: 1
